apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "chaosgenius.fullname" . }}-worker-alerts-scaler
  labels:
    deploymentName: {{ include "chaosgenius.fullname" . }}-worker-alerts
spec:
  scaleTargetRef:
    name: {{ include "chaosgenius.fullname" . }}-worker-alerts
  pollingInterval: 5
  cooldownPeriod: 120 # 2 min
  idleReplicaCount: 0 # when after polling redis list is found empty replica will be set to this count
  minReplicaCount: 1 # min replicas to scale up to when first trigger (appearance of a msg on redis list) occurs , also the number to scale down to when under thresold and not idle, idle means 0 msg 
  maxReplicaCount: 30 # max replicas will scale up to
  triggers:
    - type: redis
      metadata:
        listName: alerts
        listLength: "6"
        databaseIndex: "1"
        address: {{ .Values.redis_svc_name }}.default:6379
        # addressFromEnv: REDIS_ADDRESS

