apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chaosgenius.fullname" . }}-worker-analytics
  namespace: {{ include "chaosgenius.namespace" . }}
  labels:
    {{- include "chaosgenius.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.worker_analytics_envs }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}