apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaosgenius.fullname" . }}
  labels:
    {{- include "chaosgenius.labelsServer" . | nindent 4 }}
spec:
  type: {{ .Values.backend.server.service.type }}
  ports:
    - port: {{ .Values.backend.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chaosgenius.selectorLabelsServer" . | nindent 4 }}
