apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaosgenius.fullname" . }}-webapp
  labels:
    {{- include "chaosgenius.labelsWebapp" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chaosgenius.selectorLabelsWebapp" . | nindent 4 }}
